# Generated by Django 4.0.6 on 2022-08-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usercats_remove_profile_yandex_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercats',
            old_name='user',
            new_name='usr',
        ),
    ]
